# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/Practice 2/Practice 2.srcs/sources_1/ip/prgrom/prgrom.xci
# IP: The module: 'prgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/Practice 2/Practice 2.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgrom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/Practice 2/Practice 2.srcs/sources_1/ip/prgrom/prgrom.xci
# IP: The module: 'prgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/Practice 2/Practice 2.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
