# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/Practice 2/Practice 2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/Practice 2/Practice 2.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/Practice 2/Practice 2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/prgrom32.coe}}
add_files {{C:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/Practice 2/Practice 2.srcs/sources_1/ip/prgrom/prgrom32.coe}}
read_verilog -library xil_defaultlib {{C:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/Practice 2/Practice 2.srcs/sources_1/new/m_inst.v}}
read_ip -quiet {{C:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/Practice 2/Practice 2.srcs/sources_1/ip/prgrom/prgrom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Lab/Week 8/Practice 2/Practice 2.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top m_inst -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef m_inst.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file m_inst_utilization_synth.rpt -pb m_inst_utilization_synth.pb"
